-- =========================================================
-- ATAL LIBRARY - ATTENDANCE TABLE
-- Run this once in Supabase SQL Editor.
-- =========================================================

create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    user_id text,
    name text not null,
    email text not null,
    entry_time timestamptz not null default now(),
    exit_time timestamptz,
    status text not null default 'INSIDE'
        check (status in ('INSIDE', 'OUTSIDE'))
);

create index if not exists attendance_email_idx
    on public.attendance (email);

create index if not exists attendance_entry_time_idx
    on public.attendance (entry_time desc);

-- If RLS is enabled, the backend uses the Supabase service-role key,
-- so these API requests can still access the table.